### ISSUE TITLE
Can not build in C++

### ISSUE THREAD

**Issue by jinq0123** [wasppdotorg/hiredis-for-windows#1]
xkeycheck forbids to #define inline : 
<pre>
1>c:\program files (x86)\microsoft visual studio 14.0\vc\include\xkeycheck.h(203): warning C4005: “inline”: 宏重定义
1>  d:\jinq\git\gianttech\server_oschina\deps\hiredis-for-windows_490671\hiredis\win32.h(6): note: 参见“inline”的前一个定义
1>c:\program files (x86)\microsoft visual studio 14.0\vc\include\xkeycheck.h(250): fatal error C1189: #error:  The C++ Standard Library forbids macroizing keywords. Enable warning C4005 to find the forbidden macro.
</pre>

**Comment by systralabs** [comment]
Did you use the hiredis.sln file which is provided with the source code?

or you can simply remove the line:5 ~ line:7 of win32.h

I just tested latest version of visual studio community 2015 and it compiles fine.

**Comment by jinq0123** [comment]
hiredis.sln is OK because they are c files.

Other cpp project will error if try to #include <hiredis.h>.

I changed win32.h
<pre>
#if !defined(__cplusplus) && !defined(inline)
#define inline __inline
#endif
</pre>

**Comment by systralabs** [comment]
Well.. okay..

Actually, that's exactly what I did with the project "waspp" (my other project in this github)

waspp : cpp project
hiredis-for-windows : I put it under the directory "win"

Please let me know if there's any.

**Comment by wasppdotorg** [comment]
Well.. I just realized..

I wrote comment with my other github account, haha.
