### ISSUE TITLE
redisAsyncConnect() failed

### ISSUE THREAD

**Issue by jinq0123** [wasppdotorg/hiredis-for-windows#2]
redisAsyncConnect() failed:
```redisAsyncContext *con = redisAsyncConnect( "127.0.0.1", 7000 );```

Because set NODELAY failed:
```    if (setsockopt(c->fd, IPPROTO_TCP, TCP_NODELAY, (char*)&yes, sizeof(yes)) == -1) {```

```WSAGetLastError()``` returns 10022(WSAEINVAL).

If debug run, and break on setsockopt() for a while, then it will success. I guess the reason is socket is not connected when setsockopt().

Windows 7, VS2015.

**Comment by mobilegameserver** [comment]
No, with the windows, redisAsyncContext never worked for me, either.

`timeval timeval_ = { 1, 0 };

			c = redisConnectWithTimeout(host.c_str(), port, timeval_);
			if (c->err != REDIS_OK)
			{
				throw std::runtime_error("redisConnectWithTimeout failed");
			}`

**Comment by wasppdotorg** [comment]
No, with the windows, redisAsyncConnect never worked for me, either.

Here's how I made it work with my cpp project with "redisConnectWithTimeout"

```
timeval timeval_ = { 1, 0 };

c = redisConnectWithTimeout(host.c_str(), port, timeval_);
if (c->err != REDIS_OK)
{
	throw std::runtime_error("redisConnectWithTimeout failed");
}
```

**Comment by jinq0123** [comment]
I move ```redisSetTcpNoDelay(c)``` to before ```redisSetBlocking(c, 0)```:
```
		if ((s = socket(p->ai_family, p->ai_socktype, p->ai_protocol)) == -1)
			continue;

		c->fd = s;
		if (redisSetTcpNoDelay(c) != REDIS_OK)
			goto error;
		if (redisSetBlocking(c, 0) != REDIS_OK)
			goto error;
```

**Comment by wasppdotorg** [comment]
Thanks, that's great.

As you can see in README
'redis-for-windows' was from https://github.com/koenvandesande/hiredis
and forked, cause I needed windows version of hiredis only for development/testing,
NOT for the production.

Usually, I'm developing on windows, but all the live services I run are on linux.
So, for me, this was enough for development purpose.
(For linux, I don't even have to compile hiredis by myself)

I'm not really familiar with windows environment.
So, it'll be great if you can fork this repository and start your own hiredis-for-windows project.
